---
title: "GovTI"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(xlsx)
library(shiny)

```
Sidebar {.sidebar}
=====================================

```{r}
# shiny inputs defined here
# Input: Select a file ----
      fileInput("file1", "Choose xlsx File",
                multiple = TRUE,
                accept = c("text/s",
                         "text/comma-separated-values,text/plain",
                         ".csv",
                         ".xlsx"))

      # Horizontal line ----
      tags$hr()

      # Input: Checkbox if file has header ----
      checkboxInput("header", "Header", TRUE)

      # Input: Select separator ----
      radioButtons("sep", "Separator",
                   choices = c(Comma = ",",
                               Semicolon = ";",
                               Tab = "\t"),
                   selected = ",")

      # Input: Select quotes ----
      radioButtons("quote", "Quote",
                   choices = c(None = "",
                               "Double Quote" = '"',
                               "Single Quote" = "'"),
                   selected = '"')

      # Horizontal line ----
      tags$hr()

      # Input: Select number of rows to display ----
      radioButtons("disp", "Display",
                   choices = c(Head = "head",
                               All = "all"),
                   selected = "head")
```

Mudanças
=====================================  


Column {data-width=650}
-----------------------------------------------------------------------

### Resumo

```{r}

 dados <- read.xlsx(file=input$file1$datapath,
                    header=input$header,
                    sep=input$sep,
                    quote = input$quote,1)

head(dados)
```

Column {data-width=350}
-----------------------------------------------------------------------

### Primeiros

```{r}

head(dados)

```

### Últimos

```{r}

tail(dados)

```


Page 2
=====================================  

### Tabela de Dados

```{r}

```

